spring:
  # db
  datasource:
    url: jdbc:mysql://database-1.chcugkqgg3ab.ap-northeast-2.rds.amazonaws.com:3306/
    username: root
    password: minipro0611
    driver-class-name: com.mysql.cj.jdbc.Driver

